// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package odb

import ()

type Feature struct {
	ID   int64
	Flag string
}

type Player struct {
	ID       int64
	Username string
	PwHash   string
}

type Request struct {
	ID int64
}
