// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package query

import (
	"time"
)

type ActorImage struct {
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Description      string
	ShortDescription string
	Name             string
	Gender           string
	ID               int64
	Uniq             bool
}

type ActorImagesCan struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Can       string
	AIID      int64
	ID        int64
}

type ActorImagesCanBe struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	CanBe     string
	AIID      int64
	ID        int64
}

type ActorImagesContainerProperty struct {
	CreatedAt          time.Time
	UpdatedAt          time.Time
	AIID               int64
	ID                 int64
	LiquidCapacity     int32
	IsContainer        bool
	IsSurfaceContainer bool
}

type ActorImagesFoodProperty struct {
	CreatedAt  time.Time
	UpdatedAt  time.Time
	EatsInto   int64
	AIID       int64
	ID         int64
	Sustenance int32
}

type ActorImagesFurnitureProperty struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	AIID      int64
	ID        int64
	Seating   int32
}

type ActorImagesHand struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	AIID      int64
	ID        int64
	Hand      int32
}

type ActorImagesKeyword struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Keyword   string
	AIID      int64
	ID        int64
}

type ActorImagesPrimaryHand struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	AIID      int64
	ID        int64
	Hand      int32
}

type Email struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Address   string
	Verified  bool
	PID       int64
	ID        int64
}

type Help struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	HTML      string
	Raw       string
	Sub       string
	Title     string
	Category  string
	Slug      string
	PID       int64
}

type HelpRelated struct {
	RelatedSub   string
	RelatedTitle string
	RelatedSlug  string
	Slug         string
}

type HelpTag struct {
	Tag  string
	Slug string
	ID   int64
}

type OpenRequestChangeRequest struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Value     string
	Text      string
	RFID      int64
	PID       int64
	ID        int64
}

type PastRequestChangeRequest struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Value     string
	Text      string
	RFID      int64
	PID       int64
	ID        int64
}

type Player struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	PwHash    string
	Username  string
	ID        int64
}

type PlayerPermission struct {
	CreatedAt time.Time
	Name      string
	IPID      int64
	PID       int64
	ID        int64
}

type PlayerPermissionChangeHistory struct {
	CreatedAt time.Time
	Name      string
	IPID      int64
	PID       int64
	ID        int64
	Revoked   bool
}

type PlayerSetting struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Theme     string
	PID       int64
	ID        int64
}

type Request struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Type      string
	Status    string
	RPID      int64
	PID       int64
	ID        int64
}

type RequestChangeRequest struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Value     string
	Text      string
	RFID      int64
	PID       int64
	ID        int64
}

type RequestField struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Value     string
	Type      string
	Status    string
	RID       int64
	ID        int64
}

type RequestSubfield struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Value     string
	RFID      int64
	ID        int64
}

type Room struct {
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description string
	Title       string
	North       int64
	Northeast   int64
	East        int64
	Southeast   int64
	South       int64
	Southwest   int64
	West        int64
	Northwest   int64
	ID          int64
	Size        int32
	Unmodified  bool
}
