// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: request.sql

package query

import (
	"context"
	"database/sql"
)

const countOpenCharacterApplicationsForPlayer = `-- name: CountOpenCharacterApplicationsForPlayer :one
SELECT
  COUNT(*)
FROM
  requests
WHERE
  pid = ?
AND
  type = "CharacterApplication"
AND
  status != "Archived"
AND
  status != "Canceled"
`

func (q *Queries) CountOpenCharacterApplicationsForPlayer(ctx context.Context, pid int64) (int64, error) {
	row := q.queryRow(ctx, q.countOpenCharacterApplicationsForPlayerStmt, countOpenCharacterApplicationsForPlayer, pid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenRequestChangeRequestsForRequest = `-- name: CountOpenRequestChangeRequestsForRequest :one
SELECT
  COUNT(*)
FROM
  request_fields
JOIN
  open_request_change_requests ON open_request_change_requests.rfid = request_fields.id
WHERE
  request_fields.rid = ?
`

func (q *Queries) CountOpenRequestChangeRequestsForRequest(ctx context.Context, rid int64) (int64, error) {
	row := q.queryRow(ctx, q.countOpenRequestChangeRequestsForRequestStmt, countOpenRequestChangeRequestsForRequest, rid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenRequestChangeRequestsForRequestField = `-- name: CountOpenRequestChangeRequestsForRequestField :one
SELECT COUNT(*) FROM open_request_change_requests WHERE rfid = ?
`

func (q *Queries) CountOpenRequestChangeRequestsForRequestField(ctx context.Context, rfid int64) (int64, error) {
	row := q.queryRow(ctx, q.countOpenRequestChangeRequestsForRequestFieldStmt, countOpenRequestChangeRequestsForRequestField, rfid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCharacterApplicationContent = `-- name: CreateCharacterApplicationContent :exec
INSERT INTO
  character_application_content 
  (gender, name, short_description, description, backstory, rid) 
VALUES 
  ("", "", "", "", "", ?)
`

func (q *Queries) CreateCharacterApplicationContent(ctx context.Context, rid int64) error {
	_, err := q.exec(ctx, q.createCharacterApplicationContentStmt, createCharacterApplicationContent, rid)
	return err
}

const createCharacterApplicationContentReview = `-- name: CreateCharacterApplicationContentReview :exec
INSERT INTO
  character_application_content_review
  (gender, name, short_description, description, backstory, rid) 
VALUES 
  (?, ?, ?, ?, ?, ?)
`

type CreateCharacterApplicationContentReviewParams struct {
	Gender           string `json:"gender"`
	Name             string `json:"name"`
	ShortDescription string `json:"sdesc"`
	Description      string `json:"desc"`
	Backstory        string `json:"backstory"`
	RID              int64  `json:"-"`
}

func (q *Queries) CreateCharacterApplicationContentReview(ctx context.Context, arg CreateCharacterApplicationContentReviewParams) error {
	_, err := q.exec(ctx, q.createCharacterApplicationContentReviewStmt, createCharacterApplicationContentReview,
		arg.Gender,
		arg.Name,
		arg.ShortDescription,
		arg.Description,
		arg.Backstory,
		arg.RID,
	)
	return err
}

const createHistoryForCharacterApplication = `-- name: CreateHistoryForCharacterApplication :exec
INSERT INTO
  character_application_content_history
  (gender, name, short_description, description, backstory, rid, vid)
SELECT 
  gender, name, short_description, description, backstory, rid, requests.vid
FROM
  character_application_content
JOIN
  requests
ON
  requests.id = character_application_content.rid
WHERE
  character_application_content.rid = ?
`

func (q *Queries) CreateHistoryForCharacterApplication(ctx context.Context, rid int64) error {
	_, err := q.exec(ctx, q.createHistoryForCharacterApplicationStmt, createHistoryForCharacterApplication, rid)
	return err
}

const createOpenRequestChangeRequest = `-- name: CreateOpenRequestChangeRequest :exec
INSERT INTO open_request_change_requests (text, rfid, pid) VALUES (?, ?, ?)
`

type CreateOpenRequestChangeRequestParams struct {
	Text string
	RFID int64
	PID  int64
}

func (q *Queries) CreateOpenRequestChangeRequest(ctx context.Context, arg CreateOpenRequestChangeRequestParams) error {
	_, err := q.exec(ctx, q.createOpenRequestChangeRequestStmt, createOpenRequestChangeRequest, arg.Text, arg.RFID, arg.PID)
	return err
}

const createPastRequestChangeRequest = `-- name: CreatePastRequestChangeRequest :exec
INSERT INTO
  past_request_change_requests
SELECT created_at, updated_at, value, text, rfid, pid, id FROM
  request_change_requests
WHERE
  request_change_requests.id = ?
`

func (q *Queries) CreatePastRequestChangeRequest(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.createPastRequestChangeRequestStmt, createPastRequestChangeRequest, id)
	return err
}

const createRequest = `-- name: CreateRequest :execresult
INSERT INTO requests (type, pid) VALUES (?, ?)
`

type CreateRequestParams struct {
	Type string
	PID  int64
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (sql.Result, error) {
	return q.exec(ctx, q.createRequestStmt, createRequest, arg.Type, arg.PID)
}

const createRequestChangeRequest = `-- name: CreateRequestChangeRequest :exec
INSERT INTO
  request_change_requests
SELECT created_at, updated_at, value, text, rfid, pid, id FROM
  open_request_change_requests
WHERE
  open_request_change_requests.id = ?
`

func (q *Queries) CreateRequestChangeRequest(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.createRequestChangeRequestStmt, createRequestChangeRequest, id)
	return err
}

const createRequestField = `-- name: CreateRequestField :exec
INSERT INTO request_fields (value, type, status, rid) VALUES (?, ?, ?, ?)
`

type CreateRequestFieldParams struct {
	Value  string
	Type   string
	Status string
	RID    int64
}

func (q *Queries) CreateRequestField(ctx context.Context, arg CreateRequestFieldParams) error {
	_, err := q.exec(ctx, q.createRequestFieldStmt, createRequestField,
		arg.Value,
		arg.Type,
		arg.Status,
		arg.RID,
	)
	return err
}

const deleteOpenRequestChangeRequest = `-- name: DeleteOpenRequestChangeRequest :exec
DELETE FROM open_request_change_requests WHERE id = ?
`

func (q *Queries) DeleteOpenRequestChangeRequest(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteOpenRequestChangeRequestStmt, deleteOpenRequestChangeRequest, id)
	return err
}

const deleteRequestChangeRequest = `-- name: DeleteRequestChangeRequest :exec
DELETE FROM request_change_requests WHERE id = ?
`

func (q *Queries) DeleteRequestChangeRequest(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteRequestChangeRequestStmt, deleteRequestChangeRequest, id)
	return err
}

const editOpenRequestChangeRequest = `-- name: EditOpenRequestChangeRequest :exec
UPDATE open_request_change_requests SET text = ? WHERE id = ?
`

type EditOpenRequestChangeRequestParams struct {
	Text string
	ID   int64
}

func (q *Queries) EditOpenRequestChangeRequest(ctx context.Context, arg EditOpenRequestChangeRequestParams) error {
	_, err := q.exec(ctx, q.editOpenRequestChangeRequestStmt, editOpenRequestChangeRequest, arg.Text, arg.ID)
	return err
}

const getCharacterApplication = `-- name: GetCharacterApplication :one
SELECT
  character_application_content.created_at, character_application_content.updated_at, character_application_content.backstory, character_application_content.description, character_application_content.short_description, character_application_content.name, character_application_content.gender, character_application_content.rid, character_application_content.id, requests.created_at, requests.updated_at, requests.type, requests.status, requests.rpid, requests.pid, requests.id
FROM
  requests
JOIN
  character_application_content
ON
  character_application_content.rid = requests.id
WHERE
  requests.id = ?
`

type GetCharacterApplicationRow struct {
	CharacterApplicationContent CharacterApplicationContent
	Request                     Request
}

func (q *Queries) GetCharacterApplication(ctx context.Context, id int64) (GetCharacterApplicationRow, error) {
	row := q.queryRow(ctx, q.getCharacterApplicationStmt, getCharacterApplication, id)
	var i GetCharacterApplicationRow
	err := row.Scan(
		&i.CharacterApplicationContent.CreatedAt,
		&i.CharacterApplicationContent.UpdatedAt,
		&i.CharacterApplicationContent.Backstory,
		&i.CharacterApplicationContent.Description,
		&i.CharacterApplicationContent.ShortDescription,
		&i.CharacterApplicationContent.Name,
		&i.CharacterApplicationContent.Gender,
		&i.CharacterApplicationContent.RID,
		&i.CharacterApplicationContent.ID,
		&i.Request.CreatedAt,
		&i.Request.UpdatedAt,
		&i.Request.Type,
		&i.Request.Status,
		&i.Request.RPID,
		&i.Request.PID,
		&i.Request.ID,
	)
	return i, err
}

const getCharacterApplicationContent = `-- name: GetCharacterApplicationContent :one
SELECT created_at, updated_at, backstory, description, short_description, name, gender, rid, id FROM character_application_content WHERE id = ?
`

func (q *Queries) GetCharacterApplicationContent(ctx context.Context, id int64) (CharacterApplicationContent, error) {
	row := q.queryRow(ctx, q.getCharacterApplicationContentStmt, getCharacterApplicationContent, id)
	var i CharacterApplicationContent
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Backstory,
		&i.Description,
		&i.ShortDescription,
		&i.Name,
		&i.Gender,
		&i.RID,
		&i.ID,
	)
	return i, err
}

const getCharacterApplicationContentForRequest = `-- name: GetCharacterApplicationContentForRequest :one
SELECT created_at, updated_at, backstory, description, short_description, name, gender, rid, id FROM character_application_content WHERE rid = ?
`

func (q *Queries) GetCharacterApplicationContentForRequest(ctx context.Context, rid int64) (CharacterApplicationContent, error) {
	row := q.queryRow(ctx, q.getCharacterApplicationContentForRequestStmt, getCharacterApplicationContentForRequest, rid)
	var i CharacterApplicationContent
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Backstory,
		&i.Description,
		&i.ShortDescription,
		&i.Name,
		&i.Gender,
		&i.RID,
		&i.ID,
	)
	return i, err
}

const getCharacterApplicationContentReviewForRequest = `-- name: GetCharacterApplicationContentReviewForRequest :one
SELECT created_at, updated_at, name, gender, short_description, description, backstory, rid, id FROM character_application_content_review WHERE rid = ?
`

func (q *Queries) GetCharacterApplicationContentReviewForRequest(ctx context.Context, rid int64) (CharacterApplicationContentReview, error) {
	row := q.queryRow(ctx, q.getCharacterApplicationContentReviewForRequestStmt, getCharacterApplicationContentReviewForRequest, rid)
	var i CharacterApplicationContentReview
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Gender,
		&i.ShortDescription,
		&i.Description,
		&i.Backstory,
		&i.RID,
		&i.ID,
	)
	return i, err
}

const getOpenRequestChangeRequest = `-- name: GetOpenRequestChangeRequest :one
SELECT created_at, updated_at, value, text, rfid, pid, id FROM open_request_change_requests WHERE id = ?
`

func (q *Queries) GetOpenRequestChangeRequest(ctx context.Context, id int64) (OpenRequestChangeRequest, error) {
	row := q.queryRow(ctx, q.getOpenRequestChangeRequestStmt, getOpenRequestChangeRequest, id)
	var i OpenRequestChangeRequest
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Value,
		&i.Text,
		&i.RFID,
		&i.PID,
		&i.ID,
	)
	return i, err
}

const getOpenRequestChangeRequestForRequestField = `-- name: GetOpenRequestChangeRequestForRequestField :one
SELECT created_at, updated_at, value, text, rfid, pid, id FROM open_request_change_requests WHERE rfid = ?
`

func (q *Queries) GetOpenRequestChangeRequestForRequestField(ctx context.Context, rfid int64) (OpenRequestChangeRequest, error) {
	row := q.queryRow(ctx, q.getOpenRequestChangeRequestForRequestFieldStmt, getOpenRequestChangeRequestForRequestField, rfid)
	var i OpenRequestChangeRequest
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Value,
		&i.Text,
		&i.RFID,
		&i.PID,
		&i.ID,
	)
	return i, err
}

const getRequest = `-- name: GetRequest :one
SELECT created_at, updated_at, type, status, rpid, pid, id FROM requests WHERE id = ?
`

func (q *Queries) GetRequest(ctx context.Context, id int64) (Request, error) {
	row := q.queryRow(ctx, q.getRequestStmt, getRequest, id)
	var i Request
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Status,
		&i.RPID,
		&i.PID,
		&i.ID,
	)
	return i, err
}

const getRequestField = `-- name: GetRequestField :one
SELECT created_at, updated_at, value, type, status, rid, id FROM request_fields WHERE id = ?
`

func (q *Queries) GetRequestField(ctx context.Context, id int64) (RequestField, error) {
	row := q.queryRow(ctx, q.getRequestFieldStmt, getRequestField, id)
	var i RequestField
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Value,
		&i.Type,
		&i.Status,
		&i.RID,
		&i.ID,
	)
	return i, err
}

const getRequestFieldByType = `-- name: GetRequestFieldByType :one
SELECT created_at, updated_at, value, type, status, rid, id FROM request_fields WHERE type = ? AND rid = ?
`

type GetRequestFieldByTypeParams struct {
	Type string
	RID  int64
}

func (q *Queries) GetRequestFieldByType(ctx context.Context, arg GetRequestFieldByTypeParams) (RequestField, error) {
	row := q.queryRow(ctx, q.getRequestFieldByTypeStmt, getRequestFieldByType, arg.Type, arg.RID)
	var i RequestField
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Value,
		&i.Type,
		&i.Status,
		&i.RID,
		&i.ID,
	)
	return i, err
}

const getRequestFieldByTypeWithChangeRequests = `-- name: GetRequestFieldByTypeWithChangeRequests :one
SELECT
  request_fields.created_at, request_fields.updated_at, request_fields.value, request_fields.type, request_fields.status, request_fields.rid, request_fields.id, open_request_change_requests.created_at, open_request_change_requests.updated_at, open_request_change_requests.value, open_request_change_requests.text, open_request_change_requests.rfid, open_request_change_requests.pid, open_request_change_requests.id, request_change_requests.created_at, request_change_requests.updated_at, request_change_requests.value, request_change_requests.text, request_change_requests.rfid, request_change_requests.pid, request_change_requests.id
FROM
  request_fields
LEFT JOIN
  open_request_change_requests ON open_request_change_requests.rfid = request_fields.id
LEFT JOIN
  request_change_requests ON request_change_requests.rfid = request_fields.id
WHERE
  request_fields.type = ? AND request_fields.rid = ?
`

type GetRequestFieldByTypeWithChangeRequestsParams struct {
	Type string
	RID  int64
}

type GetRequestFieldByTypeWithChangeRequestsRow struct {
	RequestField             RequestField
	OpenRequestChangeRequest OpenRequestChangeRequest
	RequestChangeRequest     RequestChangeRequest
}

func (q *Queries) GetRequestFieldByTypeWithChangeRequests(ctx context.Context, arg GetRequestFieldByTypeWithChangeRequestsParams) (GetRequestFieldByTypeWithChangeRequestsRow, error) {
	row := q.queryRow(ctx, q.getRequestFieldByTypeWithChangeRequestsStmt, getRequestFieldByTypeWithChangeRequests, arg.Type, arg.RID)
	var i GetRequestFieldByTypeWithChangeRequestsRow
	err := row.Scan(
		&i.RequestField.CreatedAt,
		&i.RequestField.UpdatedAt,
		&i.RequestField.Value,
		&i.RequestField.Type,
		&i.RequestField.Status,
		&i.RequestField.RID,
		&i.RequestField.ID,
		&i.OpenRequestChangeRequest.CreatedAt,
		&i.OpenRequestChangeRequest.UpdatedAt,
		&i.OpenRequestChangeRequest.Value,
		&i.OpenRequestChangeRequest.Text,
		&i.OpenRequestChangeRequest.RFID,
		&i.OpenRequestChangeRequest.PID,
		&i.OpenRequestChangeRequest.ID,
		&i.RequestChangeRequest.CreatedAt,
		&i.RequestChangeRequest.UpdatedAt,
		&i.RequestChangeRequest.Value,
		&i.RequestChangeRequest.Text,
		&i.RequestChangeRequest.RFID,
		&i.RequestChangeRequest.PID,
		&i.RequestChangeRequest.ID,
	)
	return i, err
}

const listCharacterApplicationContentForPlayer = `-- name: ListCharacterApplicationContentForPlayer :many
SELECT
  created_at, updated_at, backstory, description, short_description, name, gender, rid, id
FROM
  character_application_content 
WHERE
  rid
IN (SELECT id FROM requests WHERE pid = ?)
`

func (q *Queries) ListCharacterApplicationContentForPlayer(ctx context.Context, pid int64) ([]CharacterApplicationContent, error) {
	rows, err := q.query(ctx, q.listCharacterApplicationContentForPlayerStmt, listCharacterApplicationContentForPlayer, pid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterApplicationContent
	for rows.Next() {
		var i CharacterApplicationContent
		if err := rows.Scan(
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Backstory,
			&i.Description,
			&i.ShortDescription,
			&i.Name,
			&i.Gender,
			&i.RID,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacterApplicationsForPlayer = `-- name: ListCharacterApplicationsForPlayer :many
SELECT
  character_application_content.created_at, character_application_content.updated_at, character_application_content.backstory, character_application_content.description, character_application_content.short_description, character_application_content.name, character_application_content.gender, character_application_content.rid, character_application_content.id, players.created_at, players.updated_at, players.pw_hash, players.username, players.id, requests.created_at, requests.updated_at, requests.type, requests.status, requests.rpid, requests.pid, requests.id
FROM
  requests
JOIN
  character_application_content
ON
  requests.id = character_application_content.rid
JOIN
  players
ON
  players.id = requests.pid
WHERE
  requests.pid = ?
AND
  requests.type = "CharacterApplication"
AND
  requests.status != "Archived"
AND
  requests.status != "Canceled"
`

type ListCharacterApplicationsForPlayerRow struct {
	CharacterApplicationContent CharacterApplicationContent
	Player                      Player
	Request                     Request
}

func (q *Queries) ListCharacterApplicationsForPlayer(ctx context.Context, pid int64) ([]ListCharacterApplicationsForPlayerRow, error) {
	rows, err := q.query(ctx, q.listCharacterApplicationsForPlayerStmt, listCharacterApplicationsForPlayer, pid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterApplicationsForPlayerRow
	for rows.Next() {
		var i ListCharacterApplicationsForPlayerRow
		if err := rows.Scan(
			&i.CharacterApplicationContent.CreatedAt,
			&i.CharacterApplicationContent.UpdatedAt,
			&i.CharacterApplicationContent.Backstory,
			&i.CharacterApplicationContent.Description,
			&i.CharacterApplicationContent.ShortDescription,
			&i.CharacterApplicationContent.Name,
			&i.CharacterApplicationContent.Gender,
			&i.CharacterApplicationContent.RID,
			&i.CharacterApplicationContent.ID,
			&i.Player.CreatedAt,
			&i.Player.UpdatedAt,
			&i.Player.PwHash,
			&i.Player.Username,
			&i.Player.ID,
			&i.Request.CreatedAt,
			&i.Request.UpdatedAt,
			&i.Request.Type,
			&i.Request.Status,
			&i.Request.RPID,
			&i.Request.PID,
			&i.Request.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCharacterApplications = `-- name: ListOpenCharacterApplications :many
SELECT 
  character_application_content.created_at, character_application_content.updated_at, character_application_content.backstory, character_application_content.description, character_application_content.short_description, character_application_content.name, character_application_content.gender, character_application_content.rid, character_application_content.id, players.created_at, players.updated_at, players.pw_hash, players.username, players.id, requests.created_at, requests.updated_at, requests.type, requests.status, requests.rpid, requests.pid, requests.id
FROM 
  requests
JOIN 
  character_application_content
ON 
  requests.id = character_application_content.rid
JOIN 
  players
ON 
  players.id = requests.pid
WHERE 
  requests.type = "CharacterApplication"
AND 
  requests.status = "Submitted"
OR 
  requests.status = "InReview"
OR 
  requests.status = "Reviewed"
`

type ListOpenCharacterApplicationsRow struct {
	CharacterApplicationContent CharacterApplicationContent
	Player                      Player
	Request                     Request
}

func (q *Queries) ListOpenCharacterApplications(ctx context.Context) ([]ListOpenCharacterApplicationsRow, error) {
	rows, err := q.query(ctx, q.listOpenCharacterApplicationsStmt, listOpenCharacterApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenCharacterApplicationsRow
	for rows.Next() {
		var i ListOpenCharacterApplicationsRow
		if err := rows.Scan(
			&i.CharacterApplicationContent.CreatedAt,
			&i.CharacterApplicationContent.UpdatedAt,
			&i.CharacterApplicationContent.Backstory,
			&i.CharacterApplicationContent.Description,
			&i.CharacterApplicationContent.ShortDescription,
			&i.CharacterApplicationContent.Name,
			&i.CharacterApplicationContent.Gender,
			&i.CharacterApplicationContent.RID,
			&i.CharacterApplicationContent.ID,
			&i.Player.CreatedAt,
			&i.Player.UpdatedAt,
			&i.Player.PwHash,
			&i.Player.Username,
			&i.Player.ID,
			&i.Request.CreatedAt,
			&i.Request.UpdatedAt,
			&i.Request.Type,
			&i.Request.Status,
			&i.Request.RPID,
			&i.Request.PID,
			&i.Request.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestFieldsForRequest = `-- name: ListRequestFieldsForRequest :many
SELECT created_at, updated_at, value, type, status, rid, id FROM request_fields WHERE rid = ?
`

func (q *Queries) ListRequestFieldsForRequest(ctx context.Context, rid int64) ([]RequestField, error) {
	rows, err := q.query(ctx, q.listRequestFieldsForRequestStmt, listRequestFieldsForRequest, rid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestField
	for rows.Next() {
		var i RequestField
		if err := rows.Scan(
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Value,
			&i.Type,
			&i.Status,
			&i.RID,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestFieldsForRequestWithChangeRequests = `-- name: ListRequestFieldsForRequestWithChangeRequests :many
SELECT
  request_fields.created_at, request_fields.updated_at, request_fields.value, request_fields.type, request_fields.status, request_fields.rid, request_fields.id, open_request_change_requests.created_at, open_request_change_requests.updated_at, open_request_change_requests.value, open_request_change_requests.text, open_request_change_requests.rfid, open_request_change_requests.pid, open_request_change_requests.id, request_change_requests.created_at, request_change_requests.updated_at, request_change_requests.value, request_change_requests.text, request_change_requests.rfid, request_change_requests.pid, request_change_requests.id
FROM
  request_fields
LEFT JOIN
  open_request_change_requests ON open_request_change_requests.rfid = request_fields.id
LEFT JOIN
  request_change_requests ON request_change_requests.rfid = request_fields.id
WHERE
  request_fields.rid = ?
`

type ListRequestFieldsForRequestWithChangeRequestsRow struct {
	RequestField             RequestField
	OpenRequestChangeRequest OpenRequestChangeRequest
	RequestChangeRequest     RequestChangeRequest
}

func (q *Queries) ListRequestFieldsForRequestWithChangeRequests(ctx context.Context, rid int64) ([]ListRequestFieldsForRequestWithChangeRequestsRow, error) {
	rows, err := q.query(ctx, q.listRequestFieldsForRequestWithChangeRequestsStmt, listRequestFieldsForRequestWithChangeRequests, rid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestFieldsForRequestWithChangeRequestsRow
	for rows.Next() {
		var i ListRequestFieldsForRequestWithChangeRequestsRow
		if err := rows.Scan(
			&i.RequestField.CreatedAt,
			&i.RequestField.UpdatedAt,
			&i.RequestField.Value,
			&i.RequestField.Type,
			&i.RequestField.Status,
			&i.RequestField.RID,
			&i.RequestField.ID,
			&i.OpenRequestChangeRequest.CreatedAt,
			&i.OpenRequestChangeRequest.UpdatedAt,
			&i.OpenRequestChangeRequest.Value,
			&i.OpenRequestChangeRequest.Text,
			&i.OpenRequestChangeRequest.RFID,
			&i.OpenRequestChangeRequest.PID,
			&i.OpenRequestChangeRequest.ID,
			&i.RequestChangeRequest.CreatedAt,
			&i.RequestChangeRequest.UpdatedAt,
			&i.RequestChangeRequest.Value,
			&i.RequestChangeRequest.Text,
			&i.RequestChangeRequest.RFID,
			&i.RequestChangeRequest.PID,
			&i.RequestChangeRequest.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForPlayer = `-- name: ListRequestsForPlayer :many
SELECT created_at, updated_at, type, status, rpid, pid, id FROM requests WHERE pid = ?
`

func (q *Queries) ListRequestsForPlayer(ctx context.Context, pid int64) ([]Request, error) {
	rows, err := q.query(ctx, q.listRequestsForPlayerStmt, listRequestsForPlayer, pid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.Status,
			&i.RPID,
			&i.PID,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacterApplicationContentBackstory = `-- name: UpdateCharacterApplicationContentBackstory :exec
UPDATE character_application_content SET backstory = ? WHERE rid = ?
`

type UpdateCharacterApplicationContentBackstoryParams struct {
	Backstory string `json:"backstory"`
	RID       int64  `json:"-"`
}

func (q *Queries) UpdateCharacterApplicationContentBackstory(ctx context.Context, arg UpdateCharacterApplicationContentBackstoryParams) error {
	_, err := q.exec(ctx, q.updateCharacterApplicationContentBackstoryStmt, updateCharacterApplicationContentBackstory, arg.Backstory, arg.RID)
	return err
}

const updateCharacterApplicationContentDescription = `-- name: UpdateCharacterApplicationContentDescription :exec
UPDATE character_application_content SET description = ? WHERE rid = ?
`

type UpdateCharacterApplicationContentDescriptionParams struct {
	Description string `json:"desc"`
	RID         int64  `json:"-"`
}

func (q *Queries) UpdateCharacterApplicationContentDescription(ctx context.Context, arg UpdateCharacterApplicationContentDescriptionParams) error {
	_, err := q.exec(ctx, q.updateCharacterApplicationContentDescriptionStmt, updateCharacterApplicationContentDescription, arg.Description, arg.RID)
	return err
}

const updateCharacterApplicationContentGender = `-- name: UpdateCharacterApplicationContentGender :exec
UPDATE character_application_content SET gender = ? WHERE rid = ?
`

type UpdateCharacterApplicationContentGenderParams struct {
	Gender string `json:"gender"`
	RID    int64  `json:"-"`
}

func (q *Queries) UpdateCharacterApplicationContentGender(ctx context.Context, arg UpdateCharacterApplicationContentGenderParams) error {
	_, err := q.exec(ctx, q.updateCharacterApplicationContentGenderStmt, updateCharacterApplicationContentGender, arg.Gender, arg.RID)
	return err
}

const updateCharacterApplicationContentName = `-- name: UpdateCharacterApplicationContentName :exec
UPDATE character_application_content SET name = ? WHERE rid = ?
`

type UpdateCharacterApplicationContentNameParams struct {
	Name string `json:"name"`
	RID  int64  `json:"-"`
}

func (q *Queries) UpdateCharacterApplicationContentName(ctx context.Context, arg UpdateCharacterApplicationContentNameParams) error {
	_, err := q.exec(ctx, q.updateCharacterApplicationContentNameStmt, updateCharacterApplicationContentName, arg.Name, arg.RID)
	return err
}

const updateCharacterApplicationContentReviewBackstory = `-- name: UpdateCharacterApplicationContentReviewBackstory :exec
UPDATE character_application_content_review SET backstory = ? WHERE rid = ?
`

type UpdateCharacterApplicationContentReviewBackstoryParams struct {
	Backstory string `json:"backstory"`
	RID       int64  `json:"-"`
}

func (q *Queries) UpdateCharacterApplicationContentReviewBackstory(ctx context.Context, arg UpdateCharacterApplicationContentReviewBackstoryParams) error {
	_, err := q.exec(ctx, q.updateCharacterApplicationContentReviewBackstoryStmt, updateCharacterApplicationContentReviewBackstory, arg.Backstory, arg.RID)
	return err
}

const updateCharacterApplicationContentReviewDescription = `-- name: UpdateCharacterApplicationContentReviewDescription :exec
UPDATE character_application_content_review SET description = ? WHERE rid = ?
`

type UpdateCharacterApplicationContentReviewDescriptionParams struct {
	Description string `json:"desc"`
	RID         int64  `json:"-"`
}

func (q *Queries) UpdateCharacterApplicationContentReviewDescription(ctx context.Context, arg UpdateCharacterApplicationContentReviewDescriptionParams) error {
	_, err := q.exec(ctx, q.updateCharacterApplicationContentReviewDescriptionStmt, updateCharacterApplicationContentReviewDescription, arg.Description, arg.RID)
	return err
}

const updateCharacterApplicationContentReviewGender = `-- name: UpdateCharacterApplicationContentReviewGender :exec
UPDATE character_application_content_review SET gender = ? WHERE rid = ?
`

type UpdateCharacterApplicationContentReviewGenderParams struct {
	Gender string `json:"gender"`
	RID    int64  `json:"-"`
}

func (q *Queries) UpdateCharacterApplicationContentReviewGender(ctx context.Context, arg UpdateCharacterApplicationContentReviewGenderParams) error {
	_, err := q.exec(ctx, q.updateCharacterApplicationContentReviewGenderStmt, updateCharacterApplicationContentReviewGender, arg.Gender, arg.RID)
	return err
}

const updateCharacterApplicationContentReviewName = `-- name: UpdateCharacterApplicationContentReviewName :exec
UPDATE character_application_content_review SET name = ? WHERE rid = ?
`

type UpdateCharacterApplicationContentReviewNameParams struct {
	Name string `json:"name"`
	RID  int64  `json:"-"`
}

func (q *Queries) UpdateCharacterApplicationContentReviewName(ctx context.Context, arg UpdateCharacterApplicationContentReviewNameParams) error {
	_, err := q.exec(ctx, q.updateCharacterApplicationContentReviewNameStmt, updateCharacterApplicationContentReviewName, arg.Name, arg.RID)
	return err
}

const updateCharacterApplicationContentReviewShortDescription = `-- name: UpdateCharacterApplicationContentReviewShortDescription :exec
UPDATE character_application_content_review SET short_description = ? WHERE rid = ?
`

type UpdateCharacterApplicationContentReviewShortDescriptionParams struct {
	ShortDescription string `json:"sdesc"`
	RID              int64  `json:"-"`
}

func (q *Queries) UpdateCharacterApplicationContentReviewShortDescription(ctx context.Context, arg UpdateCharacterApplicationContentReviewShortDescriptionParams) error {
	_, err := q.exec(ctx, q.updateCharacterApplicationContentReviewShortDescriptionStmt, updateCharacterApplicationContentReviewShortDescription, arg.ShortDescription, arg.RID)
	return err
}

const updateCharacterApplicationContentShortDescription = `-- name: UpdateCharacterApplicationContentShortDescription :exec
UPDATE character_application_content SET short_description = ? WHERE rid = ?
`

type UpdateCharacterApplicationContentShortDescriptionParams struct {
	ShortDescription string `json:"sdesc"`
	RID              int64  `json:"-"`
}

func (q *Queries) UpdateCharacterApplicationContentShortDescription(ctx context.Context, arg UpdateCharacterApplicationContentShortDescriptionParams) error {
	_, err := q.exec(ctx, q.updateCharacterApplicationContentShortDescriptionStmt, updateCharacterApplicationContentShortDescription, arg.ShortDescription, arg.RID)
	return err
}

const updateRequestFieldStatus = `-- name: UpdateRequestFieldStatus :exec
UPDATE request_fields SET status = ? WHERE id = ?
`

type UpdateRequestFieldStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateRequestFieldStatus(ctx context.Context, arg UpdateRequestFieldStatusParams) error {
	_, err := q.exec(ctx, q.updateRequestFieldStatusStmt, updateRequestFieldStatus, arg.Status, arg.ID)
	return err
}

const updateRequestFieldStatusByRequestAndType = `-- name: UpdateRequestFieldStatusByRequestAndType :exec
UPDATE request_fields SET status = ? WHERE type = ? AND rid = ?
`

type UpdateRequestFieldStatusByRequestAndTypeParams struct {
	Status string
	Type   string
	RID    int64
}

func (q *Queries) UpdateRequestFieldStatusByRequestAndType(ctx context.Context, arg UpdateRequestFieldStatusByRequestAndTypeParams) error {
	_, err := q.exec(ctx, q.updateRequestFieldStatusByRequestAndTypeStmt, updateRequestFieldStatusByRequestAndType, arg.Status, arg.Type, arg.RID)
	return err
}

const updateRequestFieldValueByRequestAndType = `-- name: UpdateRequestFieldValueByRequestAndType :exec
UPDATE request_fields SET value = ? WHERE type = ? AND rid = ?
`

type UpdateRequestFieldValueByRequestAndTypeParams struct {
	Value string
	Type  string
	RID   int64
}

func (q *Queries) UpdateRequestFieldValueByRequestAndType(ctx context.Context, arg UpdateRequestFieldValueByRequestAndTypeParams) error {
	_, err := q.exec(ctx, q.updateRequestFieldValueByRequestAndTypeStmt, updateRequestFieldValueByRequestAndType, arg.Value, arg.Type, arg.RID)
	return err
}

const updateRequestReviewer = `-- name: UpdateRequestReviewer :exec
UPDATE requests SET rpid = ? WHERE id = ?
`

type UpdateRequestReviewerParams struct {
	RPID int64
	ID   int64
}

func (q *Queries) UpdateRequestReviewer(ctx context.Context, arg UpdateRequestReviewerParams) error {
	_, err := q.exec(ctx, q.updateRequestReviewerStmt, updateRequestReviewer, arg.RPID, arg.ID)
	return err
}

const updateRequestStatus = `-- name: UpdateRequestStatus :exec
UPDATE requests SET status = ? WHERE id = ?
`

type UpdateRequestStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) error {
	_, err := q.exec(ctx, q.updateRequestStatusStmt, updateRequestStatus, arg.Status, arg.ID)
	return err
}
