// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

import (
	"database/sql"
)

type Player struct {
	PwHash    string
	Username  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ID        int64
}

type PlayerEmail struct {
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Verified  bool
	Pid       int64
	ID        int64
}

type PlayerPermission struct {
	Permission string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	Pid        int64
	ID         int64
}
