// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

import (
	"time"
)

type ActorImage struct {
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Description      string
	ShortDescription string
	Name             string
	Gender           string
	ID               int64
	Uniq             bool
}

type ActorImagesCan struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Can       string
	AIID      int64
	ID        int64
}

type ActorImagesCanBe struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	CanBe     string
	AIID      int64
	ID        int64
}

type ActorImagesContainerProperty struct {
	CreatedAt          time.Time
	UpdatedAt          time.Time
	LiquidCapacity     int32
	AIID               int64
	ID                 int64
	IsContainer        bool
	IsSurfaceContainer bool
}

type ActorImagesFoodProperty struct {
	CreatedAt  time.Time
	UpdatedAt  time.Time
	EatsInto   int64
	AIID       int64
	ID         int64
	Sustenance int32
}

type ActorImagesFurnitureProperty struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	AIID      int64
	ID        int64
	Seating   int32
}

type ActorImagesHand struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	AIID      int64
	ID        int64
	Hand      int32
}

type ActorImagesKeyword struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Keyword   string
	AIID      int64
	ID        int64
}

type ActorImagesPrimaryHand struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	AIID      int64
	ID        int64
	Hand      int32
}

type CharacterApplicationContent struct {
	CreatedAt        time.Time `json:"-"`
	UpdatedAt        time.Time `json:"-"`
	Backstory        string    `json:"backstory"`
	Description      string    `json:"desc"`
	ShortDescription string    `json:"sdesc"`
	Name             string    `json:"name"`
	Gender           string    `json:"gender"`
	RID              int64     `json:"-"`
	ID               int64     `json:"-"`
}

type CharacterApplicationContentHistory struct {
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Backstory        string
	Description      string
	ShortDescription string
	Name             string
	Gender           string
	RID              int64
	ID               int64
	VID              int32
}

type Email struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Address   string
	Verified  bool
	PID       int64
	ID        int64
}

type Help struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	HTML      string
	Raw       string
	Sub       string
	Title     string
	Category  string
	Slug      string
	PID       int64
}

type HelpRelated struct {
	RelatedSub   string
	RelatedTitle string
	RelatedSlug  string
	Slug         string
}

type HelpTag struct {
	Tag  string
	Slug string
	ID   int64
}

type Player struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	PwHash    string
	Username  string
	ID        int64
}

type PlayerPermission struct {
	CreatedAt  time.Time
	Permission string
	IPID       int64
	PID        int64
	ID         int64
}

type PlayerPermissionChangeHistory struct {
	CreatedAt  time.Time
	Permission string
	IPID       int64
	PID        int64
	ID         int64
	Revoked    bool
}

type PlayerSetting struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Theme     string
	PID       int64
	ID        int64
}

type Request struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Type      string
	Status    string
	RPID      int64
	PID       int64
	ID        int64
	VID       int32
}

type RequestComment struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt time.Time
	Text      string
	Field     string
	RID       int64
	PID       int64
	CID       int64
	ID        int64
	VID       int32
	Deleted   bool
	Resolved  bool
}

type RequestCommentHistory struct {
	CreatedAt time.Time
	Text      string
	Field     string
	RID       int64
	PID       int64
	CID       int64
	ID        int64
	VID       int32
}

type RequestStatusChangeHistory struct {
	CreatedAt time.Time
	Status    string
	RID       int64
	PID       int64
	ID        int64
	VID       int32
}

type Room struct {
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description string
	Title       string
	North       int64
	Northeast   int64
	East        int64
	Southeast   int64
	South       int64
	Southwest   int64
	West        int64
	Northwest   int64
	ID          int64
	Size        int32
	Unmodified  bool
}
