// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: player_settings.sql

package queries

import (
	"context"
)

const createPlayerSettings = `-- name: CreatePlayerSettings :exec
INSERT INTO player_settings (pid) VALUES (?)
`

func (q *Queries) CreatePlayerSettings(ctx context.Context, pid int64) error {
	_, err := q.exec(ctx, q.createPlayerSettingsStmt, createPlayerSettings, pid)
	return err
}

const getPlayerSettings = `-- name: GetPlayerSettings :one
SELECT created_at, updated_at, theme, pid, id FROM player_settings WHERE pid = ?
`

func (q *Queries) GetPlayerSettings(ctx context.Context, pid int64) (PlayerSetting, error) {
	row := q.queryRow(ctx, q.getPlayerSettingsStmt, getPlayerSettings, pid)
	var i PlayerSetting
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.PID,
		&i.ID,
	)
	return i, err
}

const updatePlayerSettingsTheme = `-- name: UpdatePlayerSettingsTheme :exec
UPDATE player_settings SET theme = ? WHERE pid = ?
`

type UpdatePlayerSettingsThemeParams struct {
	Theme string
	PID   int64
}

func (q *Queries) UpdatePlayerSettingsTheme(ctx context.Context, arg UpdatePlayerSettingsThemeParams) error {
	_, err := q.exec(ctx, q.updatePlayerSettingsThemeStmt, updatePlayerSettingsTheme, arg.Theme, arg.PID)
	return err
}
