name: Go Test
on: [push]
jobs:
  atlas:
    services:
      # Spin up a mysql:8 container to be used as the dev-database for analysis.
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: oilatlasdev
          MYSQL_ROOT_PASSWORD: pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup Go
            uses: actions/setup-go@v4
            with:
              go-version: 1.21.x
          - name: Run Tests
            run: go test ./...
