name: Deploy
on:
  push:
    tags: ["*"]
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  deploy:
    name: Deploy to Droplet
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: test
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }},GITHUB_SHA
          script: |
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
            docker stop app
            docker rm app
            docker container prune -f
            docker image prune -a -f
            docker image pull registry.digitalocean.com/petrichor/app:$(echo $GITHUB_SHA | head -c7)
            docker run -d -p 8008:8008 --name app -e DATABASE_URL="${{ secrets.DATABASE_URL }}" registry.digitalocean.com/petrichor/app:$(echo $GITHUB_SHA | head -c7)
            docker logout
